### ISSUE TITLE
Executions Graph for a flow showing all flows, not just selected flow

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#10488]
### Describe the issue

This flow has no executions but the graph is implying it does have executions.

<img width="1377" height="768" alt="Image" src="https://github.com/user-attachments/assets/e3ad29eb-1d31-463d-a50e-53ddd1fa1158" />

_Update: I have now run a new execution and it now appears. Under `/executions`, there was no executions for this flow and the graph on the flow execution page, matched all executions. Edited._

### Environment

- Kestra Version: `develop`

**Comment by MilosPaunovic** [comment]
I'd say this one is fixed via https://github.com/kestra-io/kestra/pull/10504, can you double check @wrussell1999?

**Comment by wrussell1999** [comment]
Still present on `develop` using commit 09593d9 sadly. 

Only 1 execution for `data-engineering-pipeline` (which is displayed in the list). Graph is showing 2 executions for today (1st August) - 1 success, 1 fail.

<img width="1367" height="739" alt="Image" src="https://github.com/user-attachments/assets/47558b21-7948-428d-b27e-63ed224e4d5f" />

You can see the two flows today that executed on the main execution page for context:

<img width="1349" height="756" alt="Image" src="https://github.com/user-attachments/assets/bf7addb1-2ac2-4433-9203-30eea6a1ad2c" />

**Comment by wrussell1999** [comment]
Seems the be the same for the namespace overview too:

<img width="1375" height="1107" alt="Image" src="https://github.com/user-attachments/assets/e2162706-c53d-41f2-a849-e919eaf8e57b" />

Namespace `demo` has 2 flows:
<img width="1365" height="256" alt="Image" src="https://github.com/user-attachments/assets/41657371-1ea1-4f54-b6d6-aba3811d9836" />

and only 2 executions.
<img width="1382" height="617" alt="Image" src="https://github.com/user-attachments/assets/4680aead-e12b-44b1-b307-14cfa84ad9c9" />

This graph seems to be the same between Namespaces, Flows, Executions, etc

**Comment by sceptri** [comment]
I can confirm that I am facing this issue as well.

**Comment by loicmathieu** [comment]
@nkwiatkowski as I know you had a look recently at the filter implementation, did you discover and fix this issue?
Otherwise I'll have a quick look, looks like a parameter not correctly passed.

**Comment by wrussell1999** [comment]
This seems to be working on `develop` on commit 59c9ae5 

Only thing to note is that it briefly shows all the executions before loading the correct ones. 

https://github.com/user-attachments/assets/d1341642-c48f-4867-9ca3-74b11236208d
