### ISSUE TITLE
Editor (No-code): Add hover effect on clickable items

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#12042]
### Feature description

<img width="1884" height="1013" alt="Image" src="https://github.com/user-attachments/assets/fac07175-3cf8-484a-aa5f-c20066700a77" />

**Description**:
In the no-code editor, clickable items currently have no hover feedback, which affects usability and consistency with the rest of the UI.

**Action**:
Add a hover state to clickable items using the variable `--ks-button-secondary-hover`.

**Comment by akshaywritescode** [comment]
@Nico-Kestra , would love to dive into this

**Comment by yash-1104github** [comment]
Hi @Nico-Kestra I would love to solve this issue, could you please assign to me

**Comment by Piyush-r-bhaskar** [comment]
Hey @akshaywritescode 

Thanks for your willingness to contribute. But it would be better if you could get the issue assigned before any actual work/PR.

**Comment by akshaywritescode** [comment]
> Hey [@akshaywritescode](https://github.com/akshaywritescode)
> 
> Thanks for your willingness to contribute. But it would be better if you could get the issue assigned before any actual work/PR.

thank @Piyush-r-bhaskar , i though i was the first one to comment, so issue will eventually issued to me, so i thought why waste time, but i will take care of it, from now on, and also can please explain what are the issue in flow will create if i done this, i wann aknow how flow works.

**Comment by RidhamAnand** [comment]
Hi @Nico-Kestra 
I'd like to take this issue. I’ve reviewed the description — the goal is to add a hover effect for clickable items in the no-code editor using the --ks-button-secondary-hover variable for visual feedback and consistency.

Please assign this to me — I can start working on it right away.

Thanks!

**Comment by MilosPaunovic** [comment]
Hello @akshaywritescode,

It's bold to assume the issue would go to you.

We're trying to explain the etiquette on multiple different places, so here is another attempt:

As a general open-source convention, it’s best to **first comment on the issue to express your interest** and wait until you're **assigned** before starting any work. This helps avoid overlapping efforts and keeps contributions coordinated.  

I have closed the PR you've submitted as it contained multiple completely unrelated changes pushed as part of it.

@yash-1104github I've assigned you to an issue this morning, so @RidhamAnand, you can go ahead and try to solve this one.

**Comment by akshaywritescode** [comment]
@MilosPaunovic sorry for assuming, from now on i will not move forwar untill someone will assign, but the thing is i already raised a pr of fix in which i resolved mistakely added files pr #12062, so technically this issue is resolved

**Comment by MilosPaunovic** [comment]
This issue is not resolved until it's merged to default branch, which in our case is `develop`.

Person assigned to it has a few days to submit a PR, and it will be looked at first. If there is no PR after a couple of days, that is the time when yours is going to be looked at for this issue.

**Comment by RidhamAnand** [comment]
@MilosPaunovic , thanks for assigning the issue, I am working on it

**Comment by RidhamAnand** [comment]
Ive raised the PR, Could you please review and merge it if its all good , Thanks.

**Comment by Piyush-r-bhaskar** [comment]
Thanks for the contribution @RidhamAnand
