### ISSUE TITLE
UI - Fix responsiveness of low code editor and topology UI

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4399]
### Describe the issue

The release of milestone 0.17 and the introduction of a new editor introduced a plethora of new bugs in the low code editor and the topology UI. 
I thought about creating separate issues for each of these issues but I didn't want to spam issues for each of these. 
Here's just some of the issues I found : 

- The topology UI and low code editor does not update immediately. You have to change the YAML somehow by adding newlines to force the topology UI to update. 
Steps to reproduce : 
1) Press the + button in the topology UI to create a new activity, such as Log. After creating the Log activity, the YAML will update but the topology UI does not update. 
2) Delete any activity. The topology UI does not update.
3) Disable/enable any activity. The topology UI does not update.
4) Check / Uncheck any checkable attribute using the low code editor. The state of the checkboxes does not update. When checking "disable" for example, the YAML will reflect by showing `disable: true`, but the low code editor will still show the disable as unchecked.

- The "Save" button does not save properly 
Steps to reproduce : 
1) Click on any activity in the Topology UI. 
2) Click "disable"
3) The YAML updates with the `disable: true` in the editor. 
4) Click "Save"
5) Nothing happens.

In general, most of the actions done using the topology UI and low code editor does not reflect in the topology UI and low code editor, but reflects in the YAML. Changes done directly in the YAML code reflects in the topology UI properly. 

### Environment

- Kestra Version: 0.17.13
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by MilosPaunovic** [comment]
Hi @johnkm516, 

Thank you for taking the time to write this issue and thank you for the patience. 🚀

Problem is now resolved, changes are pushed to `develop` branch of this repository, and we're on a scheduled patch release cycle every Thursday, so the first one to come you can expect `0.17.14` version to be published (maybe even sooner).

**Comment by johnkm516** [comment]
> Hi @johnkm516,
> 
> Thank you for taking the time to write this issue and thank you for the patience. 🚀
> 
> Problem is now resolved, changes are pushed to `develop` branch of this repository, and we're on a scheduled patch release cycle every Thursday, so the first one to come you can expect `0.17.14` version to be published (maybe even sooner).

@MilosPaunovic 
Hi Milo, it seems the problem still exists for Flow metadata such as adding a trigger. I'm on `0.17.14` and other than metadata adding tasks and removing tasks seems to work well.

**Comment by MilosPaunovic** [comment]
Hi @johnkm516,

Thanks again for reporting this one out! 🚀 

I've pushed a fix for it, but it nearly missed our `0.17.15` release from this morning, so it will be available on Thursday, as part of our regular patch release cycle, with version `0.17.16`.
