### ISSUE TITLE
Add displayName to flow level outputs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5476]
### Feature description

In the same way as users can define `displayName` for `inputs`:

```yaml
id: request_resources
namespace: company.team

inputs:
  - id: resource_type
    displayName: Select the resource type
    type: SELECT
    required: true
    values:
      - Access permissions
      - SaaS application
      - Development tool
      - Cloud VM

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: requested {{ inputs.resource_type }}
```

We want to support `displayName` on flow `outputs`, e.g.:

```yaml
id: request_resources
namespace: company.team

inputs:
  - id: resource_type
    displayName: Select the resource type
    type: SELECT
    required: true
    values:
      - Access permissions
      - SaaS application
      - Development tool
      - Cloud VM

tasks:
  - id: getdata
    type: io.kestra.plugin.core.debug.Return
    format: requested {{ inputs.resource_type }}

outputs:
  - id: myoutput
    type: STRING
    value: "{{ outputs.getdata.value }}"
    displayName: Final returned value
```

![image](https://github.com/user-attachments/assets/a1a2791b-b812-40c9-aac6-33db12e6ee89)

The columns we want to display for both inputs are outputs are:
- Id
- Name
- Value

**Comment by kratosmy** [comment]
Hi, @anna-geller , could I work on this issue?

**Comment by MilosPaunovic** [comment]
You can, but this issue includes work on both Java and Vue codebase. Is that something you'd like to approach?

**Comment by Musaveershaik** [comment]
key can you Assign this to me
I am comfortable with it

**Comment by MilosPaunovic** [comment]
Why don't we wait for the answer of the @kratosmy, as that question was first, if the answer is no, you can tackle it @Musaveershaik.

**Comment by kratosmy** [comment]
I am a full stack SE now, so yes.

**Comment by MilosPaunovic** [comment]
Okay, go ahead then and we'll wait for a PR to review! 🚀

**Comment by kratosmy** [comment]
@MilosPaunovic I have merged latest code and found that the display has been changed now 
![image](https://github.com/user-attachments/assets/25d5bac6-5b30-428c-8f21-ed88aa04c256)

So any different way to show "Name" column now? Maybe three columns without column name: "id/name/value"?

**Comment by MilosPaunovic** [comment]
Not sure what the question here is @kratosmy, but maybe @anna-geller could help us a bit more when she gets the chance.

**Comment by anna-geller** [comment]
@kratosmy the most important part for now will be to add `displayName` as backend property of flow outputs, we can later figure out how to show it in the UI 👍  

first thought for UI: if  the `displayName` is provided, show it in the first column instead of output ID

**Comment by kratosmy** [comment]
@anna-geller good to know

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/kestra/pull/5605

**Comment by loicmathieu** [comment]
Reverted as it causes issue with subflow with outputs, see https://github.com/kestra-io/kestra/issues/6308

**Comment by loicmathieu** [comment]
Inside the flow, we still have a `displayName` property, so to display it inside the execution overview we need to fetch the flow and get the display name for each execution output directly from the UI.

**Comment by SayedQassim** [comment]
Hi @loicmathieu , I would like to contribute to this, I went through the issue, as I see from the latest version that the output are appearing in the overview of the execution, so not sure what is pending for now. if you can elaborate please. Thank you.

**Comment by loicmathieu** [comment]
@SayedQassim inside the flow definition, outputs have a display name property.
Inside the execution, outputs have only an ID.

Inside the execution overview page, if an output has a display name inside the flow definition, it should be used instead of the ID.

**Comment by anna-geller** [comment]
@SayedQassim, this issue might be too challenging for a new contributor. Would you like to check one of the [good first issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+no%3Aassignee&type=issues) instead?

**Comment by anna-geller** [comment]
Loic to explain why: we had Cloud issue due to a wrong implementation of `displayName` last time which didn't take into account subflows, let's assign one of the core team members to this 👍

**Comment by i4iirfan** [comment]
Hi! I'd love to work on this tutorial issue—please let me know if it's still available.

**Comment by MilosPaunovic** [comment]
Hi @i4iirfan, 

Is there any progress on this one?

**Comment by MilosPaunovic** [comment]
Hi @i4iirfan,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by loicmathieu** [comment]
Outputs do have display name.
