### ISSUE TITLE
Adjust inline code blocks in the markdown plugin documentation for consistency

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5562]
### Feature description

These inline code blocks should use the grey color we use for Docs instead of the pink color:
![image](https://github.com/user-attachments/assets/e2f5b688-5ddb-43be-9149-cc094d45f210)

it should use this markdown syntax/colors:

![image](https://github.com/user-attachments/assets/416e5b5a-6a6c-4865-b1f0-c9c40eb20af8)

When adjusting this, we should make sure it works for both light and dark mode.

**Comment by anna-geller** [comment]
@sanjaykumar584 would you like to be assigned to this one?

**Comment by KishoreGhost** [comment]
@anna-geller can I work on this issue?

**Comment by anna-geller** [comment]
lt's give @sanjaykumar584 a chance first as he wanted to contribute to this area of code and started working on this in #5550 

Meanwhile, @KishoreGhost feel free to check [one of these good first issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen+no%3Aassignee+&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues)

**Comment by sanjaykumar584** [comment]
@anna-geller yes absolutely! I do wanna work on this.

**Comment by sanjaykumar584** [comment]
@anna-geller the example image you provided is from the flows documentation right? Do you want me to work on the flows? or the plugin documentation

**Comment by sanjaykumar584** [comment]
Hi @anna-geller and @MilosPaunovic,

I installed docker and cloned git, and everything runs fine but the problem is I don't it runs in production mode so that the changes I do in code is not reflecting on the webpage on localhost:8080. 

What am I doing wrong?

**Comment by anna-geller** [comment]
When you're editing a flow and you click on the documentation icon and then navigate your cursor to any plugin like the Shell plugin, you'll see the plugin documentation

**Comment by MilosPaunovic** [comment]
@sanjaykumar584 You want to follow [this](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code) guide to set everything up for the UI changes to have HMR.

**Comment by sanjaykumar584** [comment]
I did what the guide said exactly @MilosPaunovic 

![Screenshot 2024-10-21 235548](https://github.com/user-attachments/assets/be9c8d49-ffe1-4edd-97c1-fc0d33da6d12)
The contents are still not loading

![Screenshot 2024-10-21 235622](https://github.com/user-attachments/assets/59b0c324-3012-4bfa-99d6-60b1bd22cbc0)
This is the `npm run dev` server inside ui

![Screenshot 2024-10-21 235629](https://github.com/user-attachments/assets/30e67869-d49e-4135-b252-97fb0f4a445d)
This is when `docker-compose up` server

**Comment by MilosPaunovic** [comment]
Do you have any errors in the browser console?

**Comment by sanjaykumar584** [comment]
yeah I do 👇🏽
![Screenshot 2024-10-22 194505](https://github.com/user-attachments/assets/48532ba6-6767-497f-8abb-eb6a54b21b7d)
![Screenshot 2024-10-22 194544](https://github.com/user-attachments/assets/0bbe8f2e-170d-4d0b-b535-ba09147d67cd)
![Screenshot 2024-10-22 194854](https://github.com/user-attachments/assets/5d4d8799-11df-4be3-acae-3adb268f373b)
![Screenshot 2024-10-22 194912](https://github.com/user-attachments/assets/6f784130-a714-480c-9489-49e79ef53f2f)

**Comment by abhishek-khairnar-noovosoft** [comment]
@sanjaykumar584 try this in `ui/.env.development.local`
`VITE_APP_API_URL=http://localhost:8080`
i think you are putting the wrong port

**Comment by abhishekkhairnar** [comment]
@sanjaykumar584 try this in `ui/.env.development.local`
`VITE_APP_API_URL=http://localhost:8080`
i think you are putting the wrong port it should be `8080` not `8085`

**Comment by sanjaykumar584** [comment]
I fixed the errors. 
![{8FB181F0-733A-4106-93A5-DEDC49ED5D8F}](https://github.com/user-attachments/assets/2e83b32e-83b1-420c-9282-520d4e8a0baf)
but the plugin docs already looks fine, right?
@MilosPaunovic @anna-geller

**Comment by MilosPaunovic** [comment]
Yes, you are right, they seem to be amended via [this PR](https://github.com/kestra-io/kestra/pull/5564). Ca n you confirm that we can close this issue @anna-geller?

Thanks for the help @abhishekkhairnar! 🚀

**Comment by anna-geller** [comment]
no, the issue is not solved, plugin documentation still has pink inline code blocks instead of using the grey ones we have in the Docs 
![image](https://github.com/user-attachments/assets/02533d8d-70da-4edd-9e5b-4207de007d21)

**Comment by MilosPaunovic** [comment]
That's your answer @sanjaykumar584, so you can continue with this one, and use https://github.com/kestra-io/kestra/pull/5564 as a guide.

**Comment by sanjaykumar584** [comment]
@anna-geller no everything has already been fixed
![image](https://github.com/user-attachments/assets/3d77ac6d-9eb9-4ef1-8669-c07f53df5d55)

**Comment by abhishekkhairnar** [comment]
@MilosPaunovic and @anna-geller 
please check this
[`Closes #5562`](https://github.com/kestra-io/kestra/pull/5636)

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/kestra/pull/5636 thx a lot @abhishekkhairnar!
