### ISSUE TITLE
Improve the pie chart to make it responsive and add more legends

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6293]
### Feature description
Issue:
<img width="826" alt="Capture d’écran 2024-12-04 à 14 49 38" src="https://github.com/user-attachments/assets/99cf5c58-959d-4aba-a372-ece03a7dcd0c">

https://github.com/user-attachments/assets/41c650c3-e97d-4273-8c7d-d9691cf39ec4

1. Make the block responsive so that when the screen is small, the legends move below the chart.
2. Allow adding more legends without breaking the block. The idea would be to have a final legend grouping several others, and when hovering over it, the grouped legends are displayed. Reduce size text

[Figma](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=2194-29301&t=55hCnTxizl4noqw2-1)

**Comment by Shamar12334** [comment]
@MilosPaunovic , can I be assigned to this issue please. And if so, can I get more information for my solution to align with your needs.

**Comment by MilosPaunovic** [comment]
@Shamar12334 Yes, you can get assigned to this.

About more information, what is it that you'd need, apart from the description of this issue?

**Comment by Shamar12334** [comment]
Thanks @MilosPaunovic. So just to confirm, for the legends I am simply resizing to accommodate more of them, correct?

**Comment by MilosPaunovic** [comment]
This is in the description of this issue:

1. Make the block responsive so that when the screen is small, the legends move below the chart.
2. Allow adding more legends without breaking the block. The idea would be to have a final legend grouping several others, and when hovering over it, the grouped legends are displayed. Reduce size text

So that is what needs to be done here.

**Comment by MilosPaunovic** [comment]
@Shamar12334 Use this as a starting point and if you could open a PR with it, it would be great:

- In file `kestra/ui/src/components/dashboard/components/charts/legend.js`:
- Replace line 15 with the contents below:
`listContainer.classList.add("w-100", "fw-light", "legend", direction === "row" ? "small" : "tall");`

It will add proper class to the box and will be first step to solving this issue.

**Comment by Shamar12334** [comment]
Hi @MilosPaunovic,

I have implemented the code changes for line 15 as requested. I’m working on the remaining tasks and should have the full solution completed by today. I’ll keep you updated with any progress or issues.

Thanks

**Comment by MilosPaunovic** [comment]
Hey @Nico-Kestra,

So, @Shamar12334 created a PR which was merged (thanks for that by the way 🚀) to have the vertical scroll for circular charts.

Will close this issue for now, if still needs tweaks, you can open a separate one.

Closing via https://github.com/kestra-io/kestra/pull/7321.

**Comment by Ben8t** [comment]
Still happening on develop https://jam.dev/c/9dd9a5f7-be29-4ea0-a93b-d04aeb10da8c

**Comment by MilosPaunovic** [comment]
Doughnut chart on the `Dashborad` is not being squashed anymore, after some recent changes on how we handle resizing.

https://github.com/user-attachments/assets/015dffa7-e7cb-47b2-91a6-417165bcd4b0

If it still turns out to be a problem on different resolutions, let's open a new issue for it.
