### ISSUE TITLE
Flows are not well fitered when selecting a Namespace

### ISSUE THREAD

**Issue by janorga** [kestra-io/kestra#6295]
### Describe the issue

Flows are not filtered when a Namespace is selected. When selecting a Namespace from the UI the expected behaviour is to click then on "Flows" (into the selected Namespace section) and have only the list of Flows only for the referred Namespace. Instead of this, all Flows appear (no filter applied).

Example: A Namespace is selected and also tutorial flows appear on it.
![image](https://github.com/user-attachments/assets/0b92212d-92b3-4705-84d7-ee4c3076c2f1)

### Environment

- Kestra Version: v0.20 (but also detected in v0.19.x)

**Comment by MilosPaunovic** [comment]
Thanks or reporting this @janorga, I've pushed a fix for it on `develop`.

**Comment by janorga** [comment]
@MilosPaunovic hi Milos, any idea when this will be published to a Kestra release? It is still present in v0.20.7

**Comment by MilosPaunovic** [comment]
Hey @janorga, I've backported the commit in question to the branch for `0.20.x` release, so it will be included in regular maintenance release tomorrow.

**Comment by janorga** [comment]
Great! thanks.
