### ISSUE TITLE
Fetch logs from AWS lambda

### ISSUE THREAD

**Issue by NewbiZ** [kestra-io/kestra#8978]
### Feature description

While running tasks with the `"io.kestra.plugin.aws.lambda.Invoke"` plugin, logs are not fetched from the lambda. This is annoying as it essentially means these tasks are black boxes, or that you have to use a different channel to retrieve logs (e.g. cloudwatch logs).

I see multiple ways to implement this, by order of preference:
- AWS released "lambda extensions" a few years ago. Essentially this is a way to register a third party endpoint to receive logs in realtime. See https://aws.amazon.com/blogs/compute/using-aws-lambda-extensions-to-send-logs-to-custom-destinations/ for more information.
- The legacy way to fetch logs is to link the lambda to a cloudwatch log group. The lambda plugin could inspect the lambda (or expose a parameter to specify the log group) and fetch the logs from cloudwatch.
- Kestra could poll the lambda API to retrieve logs, but that is very inefficient.

A broader solution could be to allow some kind of authenticated log endpoint in kestra, so that a third party service can push log messages to a specific task execution. That would be an escape hatch for all tools and services where log fetching is not natively supported. Not ideal of course since that means these services would need network access back to the kestra instance, but at least that would be _some way_ to have logs working everywhere for those ready to go the extra mile of integrating this in their applications.

**Comment by shivamwayal37** [comment]
Hi,
I’d like to work on this issue if it’s still available.

I plan to start with a minimal approach by fetching Lambda logs from CloudWatch Logs after invocation and streaming them into the task logs, without requiring any Lambda-side changes.

Happy to adjust based on feedback. Thanks!

**Comment by shivamwayal37** [comment]
Hi,
I’ve started digging into the implementation and noticed that `io.kestra.plugin.aws.lambda.Invoke` lives in the` kestra-io/plugin-aws` repository rather than in `kestra-io/kestra`.

My plan is to implement the CloudWatch Logs–based log fetching in the plugin-aws repo and link the PR back to this issue.

Please let me know if that sounds good, or if you’d prefer a different approach. Thanks!

**Comment by loicmathieu** [comment]
@shivamwayal37 yes, even if the issue is inside the Kestra repository, the PR should be done against the plugin-aws repository which contains the task for AWS lambda

**Comment by shivamwayal37** [comment]
Thanks for confirming! I’ll proceed with the implementation in the plugin-aws repository and link the PR back to this issue.

**Comment by MilosPaunovic** [comment]
Hey @shivamwayal37, are there any updates on this?

**Comment by NewbiZ** [comment]
> Thanks for confirming! I’ll proceed with the implementation in the plugin-aws repository and link the PR back to this issue.

Could you also please link the issue?
Thanks for working on this ❤️

**Comment by shivamwayal37** [comment]
Hi @MilosPaunovic and @NewbiZ 👋

Yes — I’m actively working on this.

I’ve implemented CloudWatch Logs–based log fetching in the plugin-aws repository, where Lambda logs are fetched from CloudWatch after invocation and streamed directly into the task logs, without requiring any Lambda-side changes.

The core implementation is complete. I’m finalizing unit tests with a mocked CloudWatchLogsClient and aligning everything with existing plugin patterns.

I’ll open the PR shortly in kestra-io/plugin-aws and will link it back to this issue (#8978) as requested.

Thanks for the follow-up❤️

**Comment by shivamwayal37** [comment]
Hello,
I’ve opened a PR that adds support for fetching and logging CloudWatch Logs after AWS Lambda invocation, including a reusable CloudWatchLogs abstraction and unit test coverage.

I’d appreciate any feedback or suggestions. Happy to make adjustments as needed.

**Comment by fdelbrayelle** [comment]
Hi @shivamwayal37 👋 I had to revert your commit on main since the CI is actually still failing. Could you reopen your PR and fix the tests accordingly please? 🙏 Thanks!

**Comment by shivamwayal37** [comment]
Thanks for the heads-up and for reverting to keep main green 🙏
I’ll reopen the PR and update it to handle the failing integration tests more defensively (skip when Docker / LocalStack isn’t available in CI).
I’ll make sure the Lambda-related changes stay intact and that CI passes reliably before requesting another review.
